INPUT_PATTERN_UPPER_RIGHT_POSITION = 'Plateau:'
INPUT_PATTERN_LANDING_POSITION = 'Landing:'
INPUT_PATTERN_INSTRUCTION = 'Instructions:'

INSTRUCTION_LEFT_TURN = 'L'
INSTRUCTION_RIGHT_TURN = 'R'
INSTRUCTION_MOVE = 'M'


NORTH = 'N'
SOUTH = 'S'
WEST = 'W'
EAST = 'E'